Product.create({ name: 'Margarita', description: 'Cheese and tomato sauce', price: 80.00 })
Product.create({ name: 'Vesuvio', description: 'Ham, cheese and tomato sauce', price: 80.00 })
Product.create({ name: 'Hawaii', description: 'Pineapple, ham, cheese and tomato sauce', price: 85.00 })
Product.create({ name: 'Pepperoni', description: 'Pepperoni, cheese and tomato sauce', price: 85.00 })
Product.create({ name: 'Calzone', description: 'Ham, cheese and tomato sauce(folded)', price: 85.00 })